name: Build Workflow

on:
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  DEFAULT_NODE_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current commit (${{ github.sha }})
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.DEFAULT_NODE_VERSION }}

    - name: Install dependencies
      run: yarn install

    - name: Build, Minify, and Uglify
      run: yarn build
